name: TradingCards
main: com.inceris.tradingcards.TradingCards
version: 1.2.0
api-version: 1.17
author: Inceris
commands:
   tradingcards:
      description: TradingCards main command
      permission: tradingcards.use