name: RuneCraftUtilities
main: com.inceris.runecraftutilities.RuneCraftUtilities
version: 1.0.0
api-version: 1.18
author: Inceris
depend: [Boss, WorldGuard, WorldEdit]
commands:
   RuneCraftUtilities:
      description: RuneCraftUtilities command
      permission: runecraftutilities.use
      aliases: [rcu]