name: Template
main: com.inceris.trasnferaccount.TrasnferAccount
version: 0.0.0
api-version: 1.18
author: Inceris
commands:
   transferaccount:
      description: Main command
      permission: transferaccount.use