items:
    superpick:
        name: "&a&lSUPERPICK"
        durability: 100
        lore:
        - "&7Breaks blocks in a 3x3x3 area"
    grapplinghook:
        name: "&e&lGrappling Hook"
        lore:
        - "&7Pulls you toward the target location"
    flytoken:
        name: "&b&lFly Token"
        lore:
        - "&7Grants &9/fly &7for 24 hours"
    ranktoken:
        name: "&6&lRank Token"
        lore:
        - "&7Upgrade your donor rank"
    mobfreezer:
        name: "&9&lMob Freezer"
        lore:
        - "&7Freeze the nearest mob"
    disguisecap:
        name: "&e&lDisguise Cap"
        lore:
        - "&7Disguise yourself as a"
        - "&7random peaceful animal"
    cupidsbow:
        name: "&c&lCupid's Bow"
        lore:
        - "&7Makes the target lovesick."
    chocolatebar:
        name: "&a&lChocolate Bar"
        lore:
        - "&7Heals you."
    pulsingheart:
        name: "&c&lPulsing Heart"
        lore:
        - "&7Hearts effect while holding."
    cupidswings:
        name: "&c&lCupid's Wings"
        lore:
        - "&7Hearts effect while wearing."
    loveisblind:
        name: "&c&lLove is Blind"
        lore:
        - "&7Inflicts blinded and slowed."
    brokenheart:
        name: "&4&lBroken Heart"
        lore:
        - "&7Inflicts poison."
    stargazer:
        name: "&9&lStargazer"
        lore:
        - "&7Makes you glow while holding."
    pokeball:
        name: "&9&lPokeball"
        lore:
        - "&7Catch a mob and release it later."
    doubleedgedsword:
        name: "&c&lDouble-Edged Sword"
        lore:
        - "&7Nothing good ever came free."
    runecraftessence:
        name: "&b&lRunecraft Essence"
        lore:
        - "&7Makes you faster when held."
    totemofrunecraft:
        name: "&d&lTotem of Runecraft"
        lore:
        - "&7Like an enchanted gapple but better."
    invisibilitycloak:
        name: "&8&lInvisibility Cloak"
        lore:
        - "&7Makes you invisible while wearing."
    thunderbow:
        name: "&6&lThunder Bow"
        lore:
        - "&7Has a chance to strike lightning where you hit."
    thunderstone:
        name: "&6&lThunderstone"
        lore:
        - "&7Turns creepers into charged creepers."
    areschestplate:
        name: "&4&lAres' Chestplate"
        lore:
        - "&7Gives you strength and regeneration while wearing."
    obsidianiksteacup:
        name: "&d&lObsidianik's Teacup"
        lore:
        - "&7Gives you strength, resistance and regeneration."
    brolysrage:
        name: "&4&lBroly's Rage"
        lore:
        - "&7Gives you massive strength at cost of your health."
    smgsstaff:
        name: "&e&lSMG's Staff"
        lore:
        - "&7Inflicts nausea and weakness on nearby players."
    thering:
        name: "&6&lThe Ring"
        lore:
        - "&7Makes you invisible ... at a price."
    kfc:
        name: "&4&lKFC"
        lore:
        - "&7Endless finger-licking-good food."
    medusasrose:
        name: "&4&lMedusa's Rose"
        lore:
        - "&7Gives you strength at cost of your health."
    lokissceptre:
        name: "&6&lLoki's Sceptre"
        lore:
        - "&7Turns you invisible while confusing nearby players."
    escobarssalt:
        name: "&e&lEscobar's Salt"
        lore:
        - "&7Confuses a target."
    vaccine:
        name: "&a&lVaccine"
        lore:
        - "&7Removes effects from players in a large radius."