items:
    superpick:
        name: "&a&lSUPERPICK"
        durability: 100
        lore:
        - "&7Breaks blocks in a 3x3x3 area"
    grapplinghook:
        name: "&e&lGrappling Hook"
        lore:
        - "&7Pulls you toward the target location"
    flytoken:
        name: "&b&lFly Token"
        lore:
        - "&7Grants &9/fly &7for 24 hours"