items:
    superpick:
        name: "&a&lSUPERPICK"
        durability: 100
        lore:
        - "&7Breaks blocks in a 3x3x3 area"
    grapplinghook:
        name: "&e&lGrappling Hook"
        lore:
        - "&7Pulls you toward the target location"
    flytoken:
        name: "&b&lFly Token"
        lore:
        - "&7Grants &9/fly &7for 24 hours"
    ranktoken:
        name: "&6&lRank Token"
        lore:
        - "&7Upgrade your donor rank"
    mobfreezer:
        name: "&9&lMob Freezer"
        lore:
        - "&7Freeze the nearest mob"
    disguisecap:
        name: "&e&lDisguise Cap"
        lore:
        - "&7Disguise yourself as a"
        - "&7random peaceful animal"
    cupidsbow:
        name: "&c&lCupid's Bow"
        lore:
        - "&7Makes the target lovesick."
    chocolatebar:
        name: "&a&lChocolate Bar"
        lore:
        - "&7Heals you."
    pulsingheart:
        name: "&c&lPulsing Heart"
        lore:
        - "&7Hearts effect while holding."
    cupidswings:
        name: "&c&lCupid's Wings"
        lore:
        - "&7Hearts effect while wearing."
    loveisblind:
        name: "&c&lLove is Blind"
        lore:
        - "&7Inflicts blinded and slowed."
    brokenheart:
        name: "&4&lBroken Heart"
        lore:
        - "&7Inflicts poison."
    stargazer:
        name: "&9&lStargazer"
        lore:
        - "&7Makes you glow while holding."