items:
    superpick:
        name: "&a&lSUPERPICK"
        durability: 100
        lore:
        - "&7Breaks blocks in a 3x3x3 area"
    grapplinghook:
        name: "&e&lGrappling Hook"
        lore:
        - "&7Pulls you toward the target location"
    flytoken:
        name: "&b&lFly Token"
        lore:
        - "&7Grants &9/fly &7for 24 hours"
    ranktoken:
        name: "&6&lRank Token"
        lore:
        - "&7Upgrade your donor rank"
    mobfreezer:
        name: "&9&lMob Freezer"
        lore:
        - "&7Freeze the nearest mob"
    disguisecap:
        name: "&e&lDisguise Cap"
        lore:
        - "&7Disguise yourself as a"
        - "&7random peaceful animal"
    eyeofthedragon:
        name: "&5&lEye of the Dragon"
        lore:
        - "&7A re-usable ender pearl."