name: RuneCraftItems
main: com.inceris.runecraftitems.RuneCraftItems
version: 1.1.1
api-version: 1.18
author: Inceris
depend: [WorldGuard, WorldEdit, SuperTrailsPro, Vault]
commands:
   RuneCraftItems:
      description: Master command for RuneCraftItems
      permission: runecraftitems.use
      aliases: [rci]