name: RuneCraftItems
main: com.inceris.runecraftitems.RuneCraftItems
version: 0.0.0
api-version: 1.18
author: Inceris
depend: [WorldGuard, WorldEdit, SuperTrailsPro]
commands:
   RuneCraftItems:
      description: Master command for RuneCraftItems
      permission: runecraftitems.use
      aliases: [rci]