name: ATSUtilities
main: com.inceris.atsutilities.ATSUtilities
version: 1.11.3
api-version: 1.19
author: Inceris
depend: [LuckPerms, WorldEdit, WorldGuard]
commands:
   atsutilities:
      description: Main command
      usage: /<command> [subcommand]
      permission: atsutil.use
      permission-message: You don't have <permission>
      aliases: [atsu]
   atsrtp:
      description: Randomly releports to a slected biome
      usage: /<command> [player] [world] [radius] [biome]
      permission: atsutil.use
      permission-message: You don't have <permission>
   broadcast:
      description: Broadcasts a message to the whole server
      permission: atsutil.bc
      permission-message: You don't have <permission>
      aliases: [bc]
   blink:
      description: A short-range forward teleport that can't go through walls
      permission: atsutil.blink
      permission-message: You don't have <permission>
   leap:
      description: Leap in the direction you're moving
      permission: atsutil.leap
      permission-message: You don't have <permission>
   wb:
      description: Welcome a player back to the server
      permission: atsutil.use
      permission-message: You don't have <permission>
      aliases: [welcome]
   brewatrandom:
      description: Brew two random potions
      permission: atsutil.brewatrandom
      permission-message: You don't have <permission>
   countdown:
      description: Counts down
      permission: atsutil.countdown
      permission-message: You don't have <permission>
      aliases: [cd]