name: Lockout
main: com.inceris.lockout.Lockout
version: 0.2.6
api-version: 1.18
author: Inceris
depend: [Multiverse-Core, Multiverse-NetherPortals]
commands:
   lockout:
      description: Lockout command
      permission: lockout.use
